<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'seo_title_no_city' => 'Каталог акций, распродаж, скидок.',
    'seo_description_no_city' => 'Список акционных товаров, распродажи, скидки от фирм и магазинов. Актуальные горячие акции, скидки, распродажи различных товаров. Акционные предложения от всех магазинов. Выгодные покупки, ограниченные предложения товаров и др.',
    
    'seo_title' => 'Каталог акций, распродаж, скидок в городе {cityTitle}',
    'seo_description' => 'Список акционных товаров, распродажи, скидки от фирм и магазинов города {cityTitle}. Актуальные горячие акции, скидки, распродажи различных товаров в городе {cityTitle}. Акционные предложения от всех магазинов города {cityTitle}. Выгодные покупки, ограниченные предложения товаров и др.',
    'seo_keywords' => 'Акции, распродажи, скидки, каталог предложений',
    
    'promotions' => 'aкции',
    'Promotions' => 'Акции',
    'Promotions_citys' => 'Акции городов',
    'Ending_stocks_in' => 'Завершающиеся акции {cityTitle}',
    'Ending_stocks' => 'Завершающиеся акции',
    'Where_is_the' => 'Где проводится:',
    'The_offer_is_valid' => 'Акция действует:',
    'RemainedDay' => 'Остался',
    'RemainedHour' => 'Остался',
    'Left' => 'Осталось',
    'month' => 'месяц',
    'months' => 'месяца',
    'monthss' => 'месяцев',
    'day' => 'день',
    'days' => 'дня',
    'dayss' => 'дней',
    'h' => 'час',
    'hours' => 'часа',
    'hourss' => 'часов',
    'cost' => 'Цена:',
    'remained' => 'Осталась',
    'minute' => 'минута',
    'minutes' => 'минуты',
    'minutess' => 'минут',
    'min' => 'мин.',
    'All_shares_in_{cityTitle}' => 'Все акции в {cityTitle}',
    'All_share_{cityTitle}' => 'Все акции {cityTitle}',
    'All_shares_in_city_{cityTitle}' => 'Все акции в городе {cityTitle}',
    'All_shares' => 'Все акции',
    'All_shares_{cityTitle}' => 'Все акции города {cityTitle}',
    'Show_new_shares' => 'Показать новые акции',
    'Soon_run_out' => 'Скоро закончатся',
    'Archive_shares' => 'Архив акций',
    'Similar_shares_of_headings' => 'Похожие акции из рубрики',
    'Categories_of_Shares' => 'Рубрики Акций',
    'Calendar_of_shares' => 'Календарь акций',
    'Shares' => 'Акции компании',
    'Text_on_banner' => 'Вам стало известно о важной акции в городе? Вы можете опубликовать информацию о ней на нашем сайте.',
    'Add_post' => 'Добавить акцию',
    'Edit_post' => 'Редактировать акцию',
    'Shares_{titleCategory}_{cityTitle}' => 'Акции {titleCategory} города {cityTitle}',
    'Shares_{titleCategory}' => 'Акции {titleCategory}',
    'Search_a_company' => 'Поиск компании',
    'Select_a_category' => 'Выберите категорию',
    'Enter date and time' => 'Введите дату и время',
    'Category' => 'Категория',
    'Price' => 'Цена',
    'Desc' => 'Описание',
    'Date_start' => 'Дата начала',
    'Date_end' => 'Дата окончания',
    'Form_add' => 'Добавить',
    'Form_save' => 'Сохранить',
    'Search_btn' => 'Поиск',
    'Not Found' => 'Акции не найдены',
    
    'All_shares_ge_{cityTitle}' => 'Все акции {cityTitle}',
    'Shares_ge_{titleCategory}' => 'Акции {titleCategory}',
    'Shares_ge_{titleCategory}_{cityTitle}' => 'Акции {titleCategory} {cityTitle}',

    'Action {city_ge} {category}' => 'Акции "{category}" {city_ge}',
    'Action Ukraine {category}' => 'Акции "{category}" Украины',
    'Action {city_ge}' => 'Акции {city_ge}',
    'Action Ukraine' => 'Акции Украины',

    'Action index page title {city}' => 'Каталог акций, распродаж, скидок в городе {city} - CityLife',
    'Action index page keywords {city}' => 'Акции, распродажи, скидки, {city}, CityLife',
    'Action index page title Ukraine' => 'Каталог акций, распродаж, скидок в Украине - CityLife',
    'Action index page keywords' => 'Акции, распродажи, скидки, CityLife',

    'Details' => 'Детали',
];
