<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'seo_title_no_city' => 'Каталог акцій, розпродажів, знижок.',
    'seo_description_no_city' => 'Список акційних товарів, розпродажі, знижки від фірм і магазинів. Актуальні гарячі акції, знижки, розпродажі різних товарів. Акційні пропозиції від усіх магазинів. Вигідні покупки, обмежені пропозиції товарів і ін.',
    
    'seo_title' => 'Каталог акцій, розпродажів, знижок в місті {cityTitle}',
    'seo_description' => 'Список акційних товарів, розпродажі, знижки від фірм і магазинів міста {cityTitle}. Актуальні гарячі акції, знижки, розпродажі різних товарів в місті {cityTitle}. Акційні пропозиції від усіх магазинів міста {cityTitle}. Вигідні покупки, обмежені пропозиції товарів і ін.',
    'seo_keywords' => 'Акції, розпродажі, знижки, каталог пропозицій',
    
    'promotions' => 'акції',
    'Promotions' => 'Акції',
    'Promotions_citys' => 'Акції міст',
    'Ending_stocks_in' => 'Акції {cityTitle}, що завершуються',
    'Ending_stocks' => 'Акції, що завершуються',
    'Where_is_the' => 'Де проводиться:',
    'The_offer_is_valid' => 'Акція діє:',
    'RemainedDay' => 'Залишився',
    'RemainedHour' => 'Залишилась',
    'Left' => 'Залишилося',
    'month' => 'місяць',
    'months' => 'місяці',
    'monthss' => 'місяців',
    'day' => 'день',
    'days' => 'днi',
    'dayss' => 'днiв',
    'h' => 'година',
    'hours' => 'години',
    'hourss' => 'годин',
    'cost' => 'Цiна:',
    'remained' => 'Залишилася',
    'minute' => 'хвилина',
    'minutes' => 'хвилини',
    'minutess' => 'хвилин',
    'min' => 'хв.',
    'All_shares_in_{cityTitle}' => 'Усі акції в {cityTitle}',
    'All_share_{cityTitle}' => 'Усі акції {cityTitle}',
    'All_shares_in_city_{cityTitle}' => 'Усі акції в місті {cityTitle}',
    'All_shares' => 'Усі акції',
    'All_shares_{cityTitle}' => 'Усі акції міста {cityTitle}',
    'Show_new_shares' => 'Показати нові акції',
    'Soon_run_out' => 'Скоро закінчаться',
    'Archive_shares' => 'Архів акцій',
    'Similar_shares_of_headings' => 'Схожі акції з рубрики',
    'Categories_of_Shares' => 'Рубрики Акцій',
    'Calendar_of_shares' => 'Календар акцій',
    'Shares' => 'Акції компанії',
    'Text_on_banner' => 'Вам стало відомо про важливу акцію в місті? Ви можете опублікувати інформацію про неї на нашому сайті.',
    'Add_post' => 'Додати акцію',
    'Edit_post' => 'Редагувати акцию',
    'Shares_{titleCategory}_{cityTitle}' => 'Акції {titleCategory} міста {cityTitle}',
    'Shares_{titleCategory}' => 'Акції {titleCategory}',
    'Search_a_company' => 'Пошук компанії',
    'Select_a_category' => 'Оберіть категорію',
    'Enter date and time' => 'Введіть дату і час',
    'Category' => 'Категорія',
    'Price' => 'Цiна',
    'Desc' => 'Опис',
    'Date_start' => 'Дата початку',
    'Date_end' => 'Дата закінчення',
    'Form_add' => 'Додати',
    'Form_save' => 'Зберегти',
    'Search_btn' => 'Пошук',
    'Not Found' => 'Акції не знайдені',

    'All_shares_ge_{cityTitle}' => 'Усі акції {cityTitle}',
    'Shares_ge_{titleCategory}' => 'Акції {titleCategory}',
    'Shares_ge_{titleCategory}_{cityTitle}' => 'Акції "{titleCategory}" {cityTitle}',

    'Action {city_ge} {category}' => 'Акції "{category}" {city_ge}',
    'Action Ukraine {category}' => 'Акції "{category}" України',
    'Action {city_ge}' => 'Акції {city_ge}',
    'Action Ukraine' => 'Акції України',

    'Action index page title {city}' => 'Каталог акцій, розпродажів, знижок в місті {city} - CityLife',
    'Action index page keywords {city}' => 'Акції, розпродажі, знижки, {city}, CityLife',
    'Action index page title Ukraine' => 'Каталог акцій, розпродажів, знижок в Україні - CityLife',
    'Action index page keywords' => 'Акції, розпродажі, знижки, CityLife',

    'Details' => 'Деталі',
];
