<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'My_office' => 'Мой офис',
    'language_site' => 'Язык ввода: ',
    'Online' => 'В сети',
    'Profile' => 'Профиль',
    'Login' => 'Войти',
    'Logout' => 'Выйти',
    'Orders_in_business' => 'Заказы в педприятиях',
    'Orders_in_one_business' => 'Заказы в предприятия',
    'Ads' => 'Объявления',
    'Ads_active' => 'Активные объявления',
    'Advertisements' => 'Рекламная компания',
    'My_resume' => 'Мои резюме',
    'My_vacantion' => 'Мои вакансии',
    'Questions' => 'Вопросы',
    'My_purchases' => 'Мои покупки',
    'Create' => 'Добавить',
    'Update' => 'Сохранить',
    'Personal_area' => 'Личный кабинет',
    'Please_fill_the_fields' => 'Пожайлуста заполните поля для входа:',
    'Sign_in_office' => 'Вход в Офис',
    'Come_back_to_site' => 'Вернуться на сайт',
    'log' => 'Логин',
    'pass' => 'Пароль',
    'remember_me' => 'Запомнить меня',
    'If_forgotten_your_password' => 'Если вы забыли свой пароль',
    'Forgot_your_password' => 'Напомнить пароль',
    'If_you_forget_the_password' => 'Если вы забыли пароль от своего профиля',
    'forget_user_text' => 'Введите e-mail адрес, который вы указывали при регистрации. На этот адрес будет отправлен новый пароль. При желании Вы сможете потом поменять его в своем личном кабинете.',
    'Back_I_remembered_your_password' => 'Назад, я вспомнил пароль',
    'Post' => 'Сообщение!',
    'Forgot_password_ok' => 'Пароль был отправлен на указанный адреса электронной почты.',
    'Forgot_password_error' => 'К сожалению, мы не в состоянии сбросить пароль на казанный адреса электронной почты.',
    'There_is_no_user_with_such_email' => 'Пользователя с таким E-mail не найдено.',
    'Billing' => 'Биллинг',

    'Vacantion_create' => 'Создать вакансию',
    'Comments' => 'Отзывы',
    'Views' => 'Просмотры',
    'Question' => 'Вопросы',

    'Select_city' => 'Выберите город..',
    'have_problems' => 'Есть проблемы?',
    'We_believe' => 'Нас считают',
    'Save' => 'Сохранить',
    'Set a city' => 'Выберите свой город',
    'Your request {here}' => 'Ваш вопрос поставлен в очередь. Ответ можно посмотреть {here}.',
    'Sorry, we have an error' => 'Извените, возникла ошибка!',
    'Support' => 'Тех. Поддержка',

    'view' => 'Просмотр',
    'update' => 'Обновить',
    'delete' => 'Удалить',

    'Action' => 'Акции',

    'Email' => 'Емайл',

    'Email_msg_thanks_{0}' => 'Благодарим за регистрацию аккаунта на портале {0}',
    'Email_msg_success' => 'Ваш аккаунт был успешно создан',
    'Email_msg_activate' => 'Для его активации перейдите по ссылке ниже и подтвердите регистрацию',
    'Email_msg_ignore_{0}' => 'Никто, кроме Вас, его не получит и пользоваться Вашим e-mail для входа на сайт {0} не сможет',
    'Email_msg_respect' => 'С уважением ',
    'Email_msg_administration_{0}' => 'администрация сайта "{0}"',
    'Email_msg_ps' => 'P.S. Если вы получили это сообщение по ошибке, просто удалите его',

    'I_accept' => 'Принимаю условия',
    'user_Agreement' => 'пользовательского соглашения',

    'Error_required_apply' => 'Необходимо принять условия пользовательского соглашения.',
];
