<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'My_office' => 'Мій офис',
    'language_site' => 'Мова набору: ',
    'Online' => 'У мережі',
    'Profile' => 'Профіль',
    'Login' => 'Ввійти',
    'Logout' => 'Вийти',
    'Orders_in_business' => 'Замовлення в підприємствах',
    'Orders_in_one_business' => 'Замовлення в підприємстві',
    'Ads' => 'Оголошення',
    'Ads_active' => 'Активні оголошення',
    'My_resume' => 'Мої резюме',
    'My_vacantion' => 'Мої вакансії',
    'Questions' => 'Питання',
    'My_purchases' => 'Мої покупки',
    'Create' => 'Додати',
    'Update' => 'Зберегти',
    'Personal_area' => 'Особистий кабінет',
    'Please_fill_the_fields' => 'Ласка заповніть поля для входу:',
    'Sign_in_office' => 'Вход до Офiсу',
    'Come_back_to_site' => 'Повернутися на сайт',
    'log' => 'Логін',
    'pass' => 'Пароль',
    'remember_me' => "Запам'ятати мене",
    'If_forgotten_your_password' => 'Якщо ви забули свій пароль',
    'Forgot_your_password' => 'Нагадати пароль',
    'If_you_forget_the_password' => 'Якщо ви забули пароль від свого профілю',
    'forget_user_text' => 'Введіть e-mail адресу, яку ви вказали при реєстрації. На цю адресу буде відправлений новий пароль. При бажанні Ви зможете потім поміняти його в своєму особистому кабінеті.',
    'Back_I_remembered_your_password' => 'Назад, я згадав пароль',
    'Post' => 'Повідомлення!',
    'Forgot_password_ok' => 'Пароль був відправлений на вказаний адреси електронної пошти.',
    'Forgot_password_error' => 'На жаль, ми не в змозі скинути пароль на казанський адреси електронної пошти.',
    'There_is_no_user_with_such_email' => 'Користувача з таким Email не знайдене.',
    'Billing' => 'Білінг',

    'Vacantion_create' => 'Створити вакансію',
    'Comments' => 'Відгуки',
    'Views' => 'Перегляди',
    'Question' => 'Питання',

    'Select_city' => 'Виберіть місто..',
    'have_problems' => 'Є проблеми?',
    'We_believe' => 'Нас вважають',
    'Save' => 'Зберегти',
    'Set a city' => 'Виберіть своє місто',
    'Your request {here}' => 'Ваше питання поставлене в чергу. Відповідь можна подивитися {here}.',
    'Sorry, we have an error' => 'Вибачте, виникла помилка!',
    'Support' => 'Тех. Підтримка',

    'view' => 'Перегляд',
    'update' => 'Оновити',
    'delete' => 'Видалити',

    'Action' => 'Акції',

    'Email' => 'Емайл',

    'Email_msg_thanks_{0}' => 'Дякуємо за реєстрацію аккаунта на порталі {0}',
    'Email_msg_success' => 'Ваш аккаунт був успішно створений',
    'Email_msg_activate' => 'Для його активації перейдіть за посиланням нижче і підтвердіть реєстрацію',
    'Email_msg_ignore_{0}' => 'Ніхто, крім Вас, його не отримає чи користуватися Вашим e-mail для входу на сайт {0} не зможе',
    'Email_msg_respect' => 'З повагою ',
    'Email_msg_administration_{0}' => 'адміністрація сайту "{0}"',
    'Email_msg_ps' => 'P.S. Якщо ви отримали це повідомлення помилково , просто видаліть його',

    'I_accept' => 'Приймаю умови',
    'user_Agreement' => 'користувальницької угоди',

    'Error_required_apply' => 'Необхідно прийняти умови угоди.',
];
